import type { InventoryMenuItem } from "../types/inventory.types";

export const INVENTORY_MENU: InventoryMenuItem[] = [
	{
		id: "dashboard",
		label: "Dashboard Inventario",
		icon: "📊",
		path: "/inventory/dashboard",
		module: "products",
		permission: "inventory:read",
	},
	{
		id: "products",
		label: "Gestión de Productos",
		icon: "📦",
		module: "products",
		permission: "inventory:products:read",
		children: [
			{
				id: "product-catalog",
				label: "Catálogo de Productos",
				path: "/inventory/products/catalog",
				module: "products",
				permission: "inventory:products:read",
			},
			{
				id: "product-categories",
				label: "Categorías y Familias",
				path: "/inventory/products/categories",
				module: "products",
				permission: "inventory:categories:read",
			},
			{
				id: "product-brands",
				label: "Marcas y Proveedores",
				path: "/inventory/products/brands",
				module: "products",
				permission: "inventory:brands:read",
			},
			{
				id: "price-management",
				label: "Gestión de Precios",
				path: "/inventory/products/prices",
				module: "products",
				permission: "inventory:prices:manage",
			},
			{
				id: "bulk-operations",
				label: "Operaciones Masivas",
				path: "/inventory/products/bulk",
				module: "products",
				permission: "inventory:bulk:manage",
			},
		],
	},
	{
		id: "warehouses",
		label: "Gestión de Almacenes",
		icon: "🏭",
		module: "warehouses",
		permission: "inventory:warehouses:read",
		children: [
			{
				id: "warehouse-list",
				label: "Lista de Almacenes",
				path: "/inventory/warehouses/list",
				module: "warehouses",
				permission: "inventory:warehouses:read",
			},
			{
				id: "locations-zones",
				label: "Ubicaciones y Zonas",
				path: "/inventory/warehouses/locations",
				module: "warehouses",
				permission: "inventory:locations:manage",
			},
			{
				id: "stock-by-warehouse",
				label: "Stock por Almacén",
				path: "/inventory/warehouses/stock",
				module: "warehouses",
				permission: "inventory:stock:read",
			},
			{
				id: "transfers",
				label: "Transferencias entre Almacenes",
				path: "/inventory/warehouses/transfers",
				module: "warehouses",
				permission: "inventory:transfers:manage",
			},
		],
	},
	{
		id: "movements",
		label: "Movimientos de Inventario",
		icon: "🔄",
		module: "movements",
		permission: "inventory:movements:read",
		children: [
			{
				id: "entries",
				label: "Entradas de Mercancía",
				path: "/inventory/movements/entries",
				module: "movements",
				permission: "inventory:entries:manage",
			},
			{
				id: "exits",
				label: "Salidas de Mercancía",
				path: "/inventory/movements/exits",
				module: "movements",
				permission: "inventory:exits:manage",
			},
			{
				id: "adjustments",
				label: "Ajustes de Inventario",
				path: "/inventory/movements/adjustments",
				module: "movements",
				permission: "inventory:adjustments:manage",
			},
			{
				id: "movement-history",
				label: "Historial de Movimientos",
				path: "/inventory/movements/history",
				module: "movements",
				permission: "inventory:history:read",
			},
			{
				id: "kardex",
				label: "Kardex por Producto",
				path: "/inventory/movements/kardex",
				module: "movements",
				permission: "inventory:kardex:read",
			},
		],
	},
	{
		id: "reports",
		label: "Reportes e Analytics",
		icon: "📈",
		module: "reports",
		permission: "inventory:reports:read",
		children: [
			{
				id: "stock-report",
				label: "Reporte de Stock Actual",
				path: "/inventory/reports/stock",
				module: "reports",
				permission: "inventory:reports:read",
			},
			{
				id: "movement-report",
				label: "Reporte de Movimientos",
				path: "/inventory/reports/movements",
				module: "reports",
				permission: "inventory:reports:read",
			},
			{
				id: "valuation-report",
				label: "Valorización de Inventario",
				path: "/inventory/reports/valuation",
				module: "reports",
				permission: "inventory:reports:read",
			},
			{
				id: "analytics",
				label: "Analíticas Avanzadas",
				path: "/inventory/reports/analytics",
				module: "reports",
				permission: "inventory:analytics:read",
			},
		],
	},
	{
		id: "configuration",
		label: "Configuración",
		icon: "⚙️",
		module: "configuration",
		permission: "inventory:config:manage",
		children: [
			{
				id: "inventory-parameters",
				label: "Parámetros del Sistema",
				path: "/inventory/config/parameters",
				module: "configuration",
				permission: "inventory:config:manage",
			},
			{
				id: "measurement-units",
				label: "Unidades de Medida",
				path: "/inventory/config/units",
				module: "configuration",
				permission: "inventory:units:manage",
			},
			{
				id: "inventory-policies",
				label: "Políticas de Inventario",
				path: "/inventory/config/policies",
				module: "configuration",
				permission: "inventory:policies:manage",
			},
			{
				id: "barcode-config",
				label: "Configuración de Códigos de Barras",
				path: "/inventory/config/barcode",
				module: "configuration",
				permission: "inventory:barcode:manage",
			},
		],
	},
];
