/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangTestRouteImport } from './routes/$lang.test'
import { Route as LangMailRouteImport } from './routes/$lang.mail'
import { Route as LangFilesRouteImport } from './routes/$lang.files'
import { Route as LangAuthRouteImport } from './routes/$lang.auth'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangTestRoute = LangTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => LangRoute,
} as any)
const LangMailRoute = LangMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => LangRoute,
} as any)
const LangFilesRoute = LangFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/files': typeof LangFilesRoute
  '/$lang/mail': typeof LangMailRoute
  '/$lang/test': typeof LangTestRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/files': typeof LangFilesRoute
  '/$lang/mail': typeof LangMailRoute
  '/$lang/test': typeof LangTestRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/files': typeof LangFilesRoute
  '/$lang/mail': typeof LangMailRoute
  '/$lang/test': typeof LangTestRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/auth'
    | '/$lang/files'
    | '/$lang/mail'
    | '/$lang/test'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/auth'
    | '/$lang/files'
    | '/$lang/mail'
    | '/$lang/test'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/auth'
    | '/$lang/files'
    | '/$lang/mail'
    | '/$lang/test'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/test': {
      id: '/$lang/test'
      path: '/test'
      fullPath: '/$lang/test'
      preLoaderRoute: typeof LangTestRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/mail': {
      id: '/$lang/mail'
      path: '/mail'
      fullPath: '/$lang/mail'
      preLoaderRoute: typeof LangMailRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/files': {
      id: '/$lang/files'
      path: '/files'
      fullPath: '/$lang/files'
      preLoaderRoute: typeof LangFilesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAuthRoute: typeof LangAuthRoute
  LangFilesRoute: typeof LangFilesRoute
  LangMailRoute: typeof LangMailRoute
  LangTestRoute: typeof LangTestRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAuthRoute: LangAuthRoute,
  LangFilesRoute: LangFilesRoute,
  LangMailRoute: LangMailRoute,
  LangTestRoute: LangTestRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
